version: '3.5'

services:
  progvill:
    image: richarvey/nginx-php-fpm
    restart: always
    container_name: progvill
    environment:
      - VIRTUAL_HOST=progvill.hu,www.progvill.hu
      - VIRTUAL_PORT=80
      - REAL_IP_HEADER=1
      - REAL_IP_FROM=0.0.0.0/0
      - MYSQL_PORT
      - MYSQL_HOST
      - MYSQL_DB
      - MYSQL_DB_PREFIX
      - MYSQL_PASSWORD
      - MYSQL_USER
    volumes:
      - ./:/var/www/html
    networks:
      - nginx
      - mysql

networks:
  nginx:
   external: true
  mysql:
   external: true
